/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
import "sst"
export {}
declare module "sst" {
  export interface Resource {
    "Api": {
      "type": "sst.aws.ApiGatewayV2"
      "url": string
    }
    "Auth": {
      "publicKey": string
      "type": "sst.aws.Auth"
    }
    "AuthAuthenticator": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "DatabaseProvider": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "DatabaseUrl": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GoogleClientId": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GoogleClientSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MailPassword": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MailUsername": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MainEmail": {
      "configSet": string
      "sender": string
      "type": "sst.aws.Email"
    }
    "MainEmailBouncerDLQ": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "MainEmailBouncerQueue": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "MainEmailBouncerTopic": {
      "arn": string
      "type": "sst.aws.SnsTopic"
    }
    "MainEmailBucket": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "MainEmailComplaintDLQ": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "MainEmailComplaintQueue": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "MainEmailComplaintTopic": {
      "arn": string
      "type": "sst.aws.SnsTopic"
    }
    "MainEmailDeliveryDLQ": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "MainEmailDeliveryQueue": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "MainEmailDeliveryTopic": {
      "arn": string
      "type": "sst.aws.SnsTopic"
    }
    "MainEmailReceivedDLQ": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "MainEmailReceivedQueue2": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "MainEmailReceivedTopic2": {
      "arn": string
      "type": "sst.aws.SnsTopic"
    }
    "MainEmailSendDLQ": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "MainEmailSendQueue": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "MainEmailSendTopic": {
      "arn": string
      "type": "sst.aws.SnsTopic"
    }
    "RealtimeServer": {
      "authorizer": string
      "endpoint": string
      "type": "sst.aws.Realtime"
    }
    "SolidStartApp": {
      "type": "sst.aws.SolidStart"
      "url": string
    }
  }
}
